//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_development
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id_Comment { get; set; }
        public string DescriptionComment { get; set; }
        public int Id_Employee { get; set; }
        public int Id_Task { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Task Task { get; set; }
    }
}
