//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_development
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependency
    {
        public int IdDependency { get; set; }
        public int IdDependentTask { get; set; }
        public int IdCodependentTask { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Task Task1 { get; set; }
    }
}
