//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_development
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevelopmentEntities : DbContext
    {
        public DevelopmentEntities()
            : base("name=DevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssemblyType> AssemblyType { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Dependency> Dependency { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Phase> Phase { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Release> Release { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TypeOS> TypeOS { get; set; }
    }
}
